name: laborservice

on:
  pull_request:
  push:

jobs:
  laborservice:
    runs-on: ubuntu-latest

    steps:

     - name: checkout
       uses: actions/checkout@v1
     - name: Multiple line string
       run: |
          pwd
          node -v
          ls -a
       
      # - name: echo string
      #   run: echo "hello"

  #     - name: Multiple line string
  #       run: |
  #         pwd
  #         node -v
  #         ls -a
  #     - name: python command
  #       run: |
  #         import platform
  #         print(platform.processor())
  #       shell: python

  # laborserice_window:
  #    runs-on: windows-latest
  #    needs: "laborservice"
  #    steps:
  #     - name: directory
  #       run: pwd
  #       shell: bash
    
