name: laborservice

on:
  pull_request:
  push:

jobs:
  runs-on: ubuntu-latest

  steps:
    - name: echo string
      run: echo "hello"

    - name: Multiple line string
      run: |
        pwd
        node -v
        ls -a

