name: laborservice
On:
 - PR
 - PUSH
Jobs:
  runs-on laborservice:
    runs-on ubuntu-latest
    steps
      - name: echo string
        run: echo "hello"
      - name: Multiple line string
        run: |
          pwd
          node -v
          ls -a
